app:
  telegram-token: ${TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  cache:
    cache-names:
      - bucket
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

resources:
  base-url:
    scrapper: http://localhost:8080

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket4j:
  enabled: true
  filters:
    - cache-name: bucket
      url: /.*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getHeader('X-Forwarded-For')"
          bandwidths:
            - capacity: 1
              time: 1
              unit: minutes
